credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: John Smith
      password: $2b$12$LXZCyw0JNapfOKW7w5tsROVEAzOz1Fo06ecat8aCvizzIobkesVWG
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Rebecca Briggs
      password: $2b$12$sWY2WwRrHdsG9L7UBqk9bOsEbCkMRDwO8913uaN7OzzoHhfCG5qgC # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com
