credentials:
  usernames:
    tnyaruwata:
      email: tadiwamark@gmail.com
      failed_login_attempts: 0 
      logged_in: False 
      name: Tadiwanashe Nyaruwata
      password: $2b$12$LXZCyw0JNapfOKW7w5tsROVEAzOz1Fo06ecat8aCvizzIobkesVWG
    kmudzorwi:
      email: kmudzorwi@gmail.com
      failed_login_attempts: 0 
      logged_in: False 
      name: Engineer Kuzotungamira Mudzorwi
      password: $2b$12$sWY2WwRrHdsG9L7UBqk9bOsEbCkMRDwO8913uaN7OzzoHhfCG5qgC 
cookie:
  expiry_days: 30
  key: some_signature_key 
  name: some_cookie_name

